var pototeHead = ('MistPotatoeHead')
var pototeHead2 = ('MistPotatoeHead1')
var pototeHead3 = ('MistPotatoeHead2')
var pototeHead4 = ('MistPotatoeHead3')
var pototeHead5 = ('MistPotatoeHead4')
var pototeHead6 = ('MistPotatoeHead5')